#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	//print_rtable();	
	fprintf(stderr, "TODO: longest prefix match for the packet.dst:%x\n",dst);
	u32 tmp_long = 0;
	rt_entry_t* res = NULL;
	rt_entry_t* tmp = NULL;
	list_for_each_entry(tmp,&rtable,list){
		fprintf(stderr,"tmp->dest:%x\n",tmp->dest);
		if((tmp->dest & tmp->mask) == (dst & tmp->mask)){
			if(tmp->mask > tmp_long){
				res = tmp;
				tmp_long = tmp->mask;
				fprintf(stderr,"tmp_long:%u\n",tmp_long);
			}
		}
	}
	fprintf(stderr,"res\n");
	return res;
}

// send IP packet
//
// Different from ip_forward_packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	
	fprintf(stderr, "TODO: send ip packet.\n");
	struct ether_header* eH = (struct ether_header*)packet;
	eH->ether_type = htons(ETH_P_IP);
	struct iphdr* ipH = (struct iphdr*)(packet+ETHER_HDR_SIZE);
	rt_entry_t * e = longest_prefix_match(ntohl(ipH->daddr));
	if(e == NULL){
		fprintf(stderr,"Send Fail\n");
		free(packet);
		return;
	}
	memcpy(eH->ether_shost,e->iface->mac,ETH_ALEN);
	u32 nH = e->gw;
	fprintf(stderr,"nH:%x\n",nH);
	if(nH == 0){
		nH = ntohl(ipH->daddr);
	}
	ipH->saddr = htonl(e->iface->ip);
	fprintf(stderr,"e->iface->ip:%x\n",e->iface->ip);
	//memcpy(eH->ether_shost,e->iface->mac,ETH_ALEN);
	iface_send_packet_by_arp(e->iface,nH,packet,len);
}
